
async function getProduct(id: any) {
    // const response = await fetch("https://dummyjson.com/products", {
    //   cache: "no-store",
    // });
  
    const response = await fetch(`https://dummyjson.com/products/${id}`);
  
    const data = await response.json();
    return data;
  }
  

export default async function Head({ params }: any) {

    const products = await getProduct(params.id);
    const data = products;


    return (
      <>
        <title>{data?.title}</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </>
    )
  }
  