import axios from "axios";



async function getProduct(id: number) {
  interface productProps {
    title: string;
    description: string;
    price: number;
  }

    const response = await fetch(`https://dummyjson.com/products/${id}`);
    const x: any = response.json();
    return x as productProps;
}




export default async function Head({params}: any) {
  const products = await getProduct(params.id);
  const data = products;



  // console.log("header")
  return (
    <>
      <title>{data?.title}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}



// export default function Head({datad}: any) {
//   return (
//     <>
//       <title>{datad}</title>
//       <meta content="width=device-width, initial-scale=1" name="viewport" />
//       <meta name="description" content="Generated by create next app" />
//       <link rel="icon" href="/favicon.ico" />
//     </>
//   )
// }
